### ISSUE TITLE
All nextbots appear as "Error Signs".

### ISSUE THREAD

**Issue by beepsy** [IvanVladimir04/Halo-Reach-NextBots#1]
Help?

**Comment by IvanVladimir04** [comment]
Get the halo reach nextbots resources that are called required

**Comment by beepsy** [comment]
i already did but they till appear errors

**Comment by beepsy** [comment]
i have, but they still are errors.

**Comment by IvanVladimir04** [comment]
Buddy, they work for me, and have worked for other people (as in, they have spawned with models) it's something you did wrong, not me.

**Comment by beepsy** [comment]
alright, I'll try redownloading them, see what happens.
